baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung-custom.css"
margin = 0.1
transition_speed = 'fast'
highlight_theme = "foundation"

[markup.highlight]
codeFences = false
style = "rrt"
